trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'Conexion-AzureML-DataScience'
  resourceGroup: 'RscgrpMooveCars'
  workspaceName: 'PurebaML'

steps:
- task: AzureCLI@2
  displayName: "Diagnóstico conexión Azure ML"
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail
      set -x

      echo "CLI version:"
      az version

      # Asegura auto-instalación de extensiones y la 'ml'
      az config set extension.use_dynamic_install=yes_without_prompt
      az extension add -n ml -y || az extension update -n ml || true

      echo "Cuenta activa / contexto de login:"
      az account show --query "{subscription:id, user:user, tenant:tenantId}"

      echo "Listado rápido de RG para validar scope:"
      az group list --query "[].name"

      echo "Mostrar workspace AML:"
      az ml workspace show \
        --name "$(workspaceName)" \
        --resource-group "$(resourceGroup)" \
        --only-show-errors \
        --query "{name:name, location:location, id:id}"

      echo "✅ Conexión OK"

  env:
    AZURE_EXTENSION_USE_DYNAMIC_INSTALL: yes_without_prompt
